import { frameworkCatalogDigest } from "../../src/framework-catalog.js";
import { fileSha256, type ProjectFrameworkSelection } from "../../src/project.js";

/** Minimal supported catalog whose only installed effect is one exact server. */
export async function frameworkForServer(serverPath:string):Promise<ProjectFrameworkSelection>{
  const componentRef={componentId:"mirrorecma",repository:"https://example.invalid/MirrorECMA.git",revision:"1".repeat(40),dirty:false};
  const platform={os:"linux",osRelease:"test",architecture:"x86_64",backend:"local-process"};
  const catalog={schemaVersion:"mirrors.framework-catalog/v1",catalogId:"project-binding",visibility:"public",components:[{componentRef,product:{name:"mirrorecma",version:"2.0.0"},records:[{recordId:"package",path:"package.json",recordKind:"manifest"}]}],evidenceRefs:[{evidenceId:"accepted",runRef:{schemaVersion:"mirrors.evidence-public-summary/v1.0",runId:"test",envelopeSha256:"9".repeat(64),projectionKind:"public"}}],capabilities:[{capabilityId:"cap.server",ownerComponentId:"mirrorecma",description:"test",declaration:{state:"available",constraints:[]},sourceImplementation:{state:"present",locations:[{path:"src/project.ts",symbol:"replayProject"}]},observations:{sourceTested:{state:"unknown"},locallyAccepted:{state:"unknown"},installedConsumerAccepted:{state:"accepted",evidenceId:"accepted"},hostedCiAccepted:{state:"notRun"},published:{state:"unknown"}}}],distributionProfiles:[{profileId:"catalog.local",platform,requiredCapabilityIds:["cap.server"],optionalCapabilityIds:[],requiredObservationDimensions:["installedConsumerAccepted"],dependencies:[]}],combinations:[{combinationId:"supported-local",componentIds:["mirrorecma"],platform,capabilityIds:["cap.server"],distributionProfileIds:["catalog.local"],declaredState:"supported",evidenceIds:["accepted"]}]};
  const selectionRef={schemaVersion:"mirrors.framework-catalog/v1" as const,selectionKind:"sha256" as const,selectionValue:frameworkCatalogDigest(catalog)},serverSha=await fileSha256(serverPath);
  const manifest={schemaVersion:"mirrors.reference-distribution-manifest/v1",distributionId:"test",catalogSelectionRef:selectionRef,profileId:"checked",componentRefs:[componentRef],buildInputs:[{inputId:"profiles-lock",path:"profiles",bytes:1,sha256:"1".repeat(64)},{inputId:"component-lock",path:"components",bytes:1,sha256:"2".repeat(64)},{inputId:"dependency-lock",path:"dependencies",bytes:1,sha256:"3".repeat(64)}],buildProvenance:{snapshotIndexSha256:"4".repeat(64),tools:[{toolId:"node",version:"test",bytes:1,sha256:"5".repeat(64)}],trees:[]},artifacts:[{artifactId:"mirror-server",path:"bin/mirror",kind:"file",mediaType:"application/octet-stream",bytes:1,sha256:serverSha,mode:"0755",source:{kind:"component-build",id:"mirror-server"},dynamicLibraries:[{soname:"libssl.so.3",path:"/usr/lib/libssl.so.3",sha256:"c".repeat(64)}]}],runtimeTrees:[],hostRequirements:[],publication:"unclaimed"};
  const distributionManifestRaw=JSON.stringify(manifest),cache={schemaVersion:"mirrors.reference-cache-index/v1",profileId:"checked",catalogSelectionRef:selectionRef,distributionManifestSha256:frameworkCatalogDigest(manifest),entries:manifest.artifacts.map(({artifactId,path,bytes,sha256,mode})=>({artifactId,path,bytes,sha256,mode}))};
  return {catalogRaw:JSON.stringify(catalog),selectionRef,combinationId:"supported-local",observed:{distributionManifestRaw,cacheIndexRaw:JSON.stringify(cache),componentRefs:[componentRef],packages:[],executables:[{role:"mirror-server",artifactId:"mirror-server",sha256:serverSha,capabilityIds:["cap.server"]}],runtimeTrees:[],platform,policy:{admission:"support-required",manifestProfileId:"checked",catalogProfileId:"catalog.local",packages:[],executables:[{role:"mirror-server",artifactId:"mirror-server",requiredCapabilityIds:["cap.server"]}],runtimeTrees:[]}},installation:{schema:"mirrorecma.installed-framework-binding/v1",executables:[{role:"mirror-server",artifactId:"mirror-server",path:serverPath,sha256:serverSha}],packages:[],runtimeTrees:[]}};
}
