// @generated by Mirrors model_interface_gen
// target-profile: mirrorecma-async-v1
// profile-version: 1
// semantic-sha256: a0d5d0fa70f0d62dd55965407a9503b4d220ebcfdc62c0f36d46be0a837b3643
// DO NOT EDIT

import type { ApalacheConfig, AsyncStateComputer, ReplayContext, State, Value } from "mirrorecma";

export type MirrorSet<T> = readonly T[];
export type MirrorMap<K, V> = readonly (readonly [K, V])[];

type TypeShape =
  | { readonly kind: "int" | "bool" | "str" | "null" }
  | { readonly kind: "set" | "seq"; readonly element: TypeShape }
  | { readonly kind: "tuple"; readonly elements: readonly TypeShape[] }
  | { readonly kind: "record"; readonly fields: readonly (readonly [string, TypeShape])[] }
  | { readonly kind: "map"; readonly key: TypeShape; readonly value: TypeShape }
  | { readonly kind: "variant"; readonly cases: readonly (readonly [string, TypeShape])[] };

type RuntimePathSegment =
  | { readonly kind: "field"; readonly name: string }
  | { readonly kind: "index"; readonly index: number }
  | { readonly kind: "variantValue"; readonly tag: string };

function ownRecord(value: unknown): Record<string, unknown> | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[], path: string): void {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  if (actual.length !== wanted.length || actual.some((key, i) => key !== wanted[i])) {
    throw new Error(path + ": expected keys [" + wanted.join(", ") + "], got [" + actual.join(", ") + "]");
  }
}

function comparableInitialState(root: State): State {
  const filtered = Object.create(null) as State;
  for (const [name, value] of Object.entries(root)) {
    if (!name.startsWith("#") && name !== "action_taken" && name !== "parameters") {
      filtered[name] = value;
    }
  }
  return filtered;
}

function valueIdentity(value: Value): string {
  switch (value.tag) {
    case "int": return "int:" + value.val.toString();
    case "bool": return value.val ? "bool:1" : "bool:0";
    case "str": return "str:" + JSON.stringify(value.val);
    case "null": return "null";
    case "set": return "set:[" + value.val.map(valueIdentity).sort().join(",") + "]";
    case "seq": return "seq:[" + value.val.map(valueIdentity).join(",") + "]";
    case "tuple": return "tuple:[" + value.val.map(valueIdentity).join(",") + "]";
    case "record": return "record:{" + Object.keys(value.val).sort()
      .map((key) => JSON.stringify(key) + ":" + valueIdentity(value.val[key]!)).join(",") + "}";
    case "map": return "map:[" + value.val.map(([key, item]) =>
      valueIdentity(key) + "=>" + valueIdentity(item)).sort().join(",") + "]";
    case "variant": return "variant:" + JSON.stringify(value.variantTag) + "=" + valueIdentity(value.value);
    case "unserializable": return "unserializable:" + JSON.stringify(value.val);
  }
}

function assertUniqueValues(values: readonly Value[], path: string): void {
  const seen = new Set<string>();
  for (const value of values) {
    const identity = valueIdentity(value);
    if (seen.has(identity)) throw new Error(path + ": duplicate set element or map key");
    seen.add(identity);
  }
}

function readPath(root: State, path: readonly RuntimePathSegment[], label: string): Value {
  let value: Value = { tag: "record", val: root };
  for (const segment of path) {
    if (segment.kind === "field") {
      if (value.tag !== "record" || !Object.prototype.hasOwnProperty.call(value.val, segment.name)) {
        throw new Error(label + ": missing record field " + segment.name);
      }
      value = value.val[segment.name]!;
    } else if (segment.kind === "index") {
      if ((value.tag !== "seq" && value.tag !== "tuple") || segment.index >= value.val.length) {
        throw new Error(label + ": missing index " + segment.index);
      }
      value = value.val[segment.index]!;
    } else {
      if (value.tag !== "variant" || value.variantTag !== segment.tag) {
        throw new Error(label + ": expected variant " + segment.tag);
      }
      value = value.value;
    }
  }
  return value;
}

function decodeNative(value: Value, shape: TypeShape, path: string): unknown {
  switch (shape.kind) {
    case "int": if (value.tag === "int") return value.val; break;
    case "bool": if (value.tag === "bool") return value.val; break;
    case "str": if (value.tag === "str") return value.val; break;
    case "null": if (value.tag === "null") return null; break;
    case "set":
      if (value.tag === "set") return value.val.map((item, i) => decodeNative(item, shape.element, path + "[" + i + "]"));
      break;
    case "seq":
      if (value.tag === "seq") return value.val.map((item, i) => decodeNative(item, shape.element, path + "[" + i + "]"));
      break;
    case "tuple":
      if (value.tag === "tuple" && value.val.length === shape.elements.length) {
        return value.val.map((item, i) => decodeNative(item, shape.elements[i]!, path + "[" + i + "]"));
      }
      break;
    case "record":
      if (value.tag === "record") {
        exactKeys(value.val, shape.fields.map(([name]) => name), path);
        const out = Object.create(null) as Record<string, unknown>;
        for (const [name, fieldShape] of shape.fields) {
          out[name] = decodeNative(value.val[name]!, fieldShape, path + "." + name);
        }
        return out;
      }
      break;
    case "map":
      if (value.tag === "map") return value.val.map(([key, item], i) => [
        decodeNative(key, shape.key, path + "[" + i + "].key"),
        decodeNative(item, shape.value, path + "[" + i + "].value"),
      ] as const);
      break;
    case "variant":
      if (value.tag === "variant") {
        const found = shape.cases.find(([tag]) => tag === value.variantTag);
        if (found) return {
          tag: value.variantTag,
          value: decodeNative(value.value, found[1], path + ".value"),
        };
      }
      break;
  }
  throw new Error(path + ": value does not match " + shape.kind);
}

function encodeNative(value: unknown, shape: TypeShape, path: string): Value {
  switch (shape.kind) {
    case "int": if (typeof value === "bigint") return { tag: "int", val: value }; break;
    case "bool": if (typeof value === "boolean") return { tag: "bool", val: value }; break;
    case "str": if (typeof value === "string") return { tag: "str", val: value }; break;
    case "null": if (value === null) return { tag: "null" }; break;
    case "set":
    case "seq":
      if (Array.isArray(value)) {
        const val = value.map((item, i) => encodeNative(item, shape.element, path + "[" + i + "]"));
        if (shape.kind === "set") assertUniqueValues(val, path);
        return shape.kind === "set" ? { tag: "set", val } : { tag: "seq", val };
      }
      break;
    case "tuple":
      if (Array.isArray(value) && value.length === shape.elements.length) {
        return {
          tag: "tuple",
          val: value.map((item, i) => encodeNative(item, shape.elements[i]!, path + "[" + i + "]")),
        };
      }
      break;
    case "record": {
      const record = ownRecord(value);
      if (record) {
        exactKeys(record, shape.fields.map(([name]) => name), path);
        const val = Object.create(null) as Record<string, Value>;
        for (const [name, fieldShape] of shape.fields) {
          val[name] = encodeNative(record[name], fieldShape, path + "." + name);
        }
        return { tag: "record", val };
      }
      break;
    }
    case "map":
      if (Array.isArray(value)) {
        const val: [Value, Value][] = value.map((entry, i) => {
          if (!Array.isArray(entry) || entry.length !== 2) {
            throw new Error(path + "[" + i + "]: expected map entry");
          }
          return [
            encodeNative(entry[0], shape.key, path + "[" + i + "].key"),
            encodeNative(entry[1], shape.value, path + "[" + i + "].value"),
          ];
        });
        assertUniqueValues(val.map(([key]) => key), path);
        return { tag: "map", val };
      }
      break;
    case "variant": {
      const variant = ownRecord(value);
      if (variant && typeof variant.tag === "string") {
        exactKeys(variant, ["tag", "value"], path);
        const found = shape.cases.find(([tag]) => tag === variant.tag);
        if (found) return {
          tag: "variant",
          variantTag: variant.tag,
          value: encodeNative(variant.value, found[1], path + ".value"),
        };
      }
      break;
    }
  }
  throw new Error(path + ": implementation value does not match " + shape.kind);
}

export interface AcquireInput {
  readonly client: bigint;
}

export interface AdvanceInput {
  readonly amount: bigint;
}

export interface ReleaseInput {
  readonly client: bigint;
  readonly token: bigint;
}

export interface RenewInput {
  readonly client: bigint;
  readonly token: bigint;
}

export interface WriteInput {
  readonly client: bigint;
  readonly token: bigint;
}

export interface LeaseServiceObservation {
  readonly accepted: boolean;
  readonly epoch: bigint;
  readonly expires: bigint;
  readonly now: bigint;
  readonly owners: MirrorSet<bigint>;
  readonly writes: bigint;
}

export interface LeaseServiceAsyncPort {
  initialize(context: ReplayContext): Promise<void>;
  acquire(input: AcquireInput, context: ReplayContext): Promise<void>;
  advance(input: AdvanceInput, context: ReplayContext): Promise<void>;
  release(input: ReleaseInput, context: ReplayContext): Promise<void>;
  renew(input: RenewInput, context: ReplayContext): Promise<void>;
  write(input: WriteInput, context: ReplayContext): Promise<void>;
  observe(context: ReplayContext): Promise<LeaseServiceObservation>;
}

const acquire_ClientShape: TypeShape = { kind: "int" };

const advance_AmountShape: TypeShape = { kind: "int" };

const release_ClientShape: TypeShape = { kind: "int" };

const release_TokenShape: TypeShape = { kind: "int" };

const renew_ClientShape: TypeShape = { kind: "int" };

const renew_TokenShape: TypeShape = { kind: "int" };

const write_ClientShape: TypeShape = { kind: "int" };

const write_TokenShape: TypeShape = { kind: "int" };

const leaseServiceAcceptedObservationShape: TypeShape = { kind: "bool" };

const leaseServiceEpochObservationShape: TypeShape = { kind: "int" };

const leaseServiceExpiresObservationShape: TypeShape = { kind: "int" };

const leaseServiceNowObservationShape: TypeShape = { kind: "int" };

const leaseServiceOwnersObservationShape: TypeShape = { kind: "set", element: { kind: "int" } };

const leaseServiceWritesObservationShape: TypeShape = { kind: "int" };

function decodeAcquireInput(payload: State): AcquireInput {
  return {
    client: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "client" }], "Acquire.Client"), acquire_ClientShape, "Acquire.Client") as bigint,
  };
}

function decodeAdvanceInput(payload: State): AdvanceInput {
  return {
    amount: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "amount" }], "Advance.Amount"), advance_AmountShape, "Advance.Amount") as bigint,
  };
}

function decodeReleaseInput(payload: State): ReleaseInput {
  return {
    client: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "client" }], "Release.Client"), release_ClientShape, "Release.Client") as bigint,
    token: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "token" }], "Release.Token"), release_TokenShape, "Release.Token") as bigint,
  };
}

function decodeRenewInput(payload: State): RenewInput {
  return {
    client: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "client" }], "Renew.Client"), renew_ClientShape, "Renew.Client") as bigint,
    token: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "token" }], "Renew.Token"), renew_TokenShape, "Renew.Token") as bigint,
  };
}

function decodeWriteInput(payload: State): WriteInput {
  return {
    client: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "client" }], "Write.Client"), write_ClientShape, "Write.Client") as bigint,
    token: decodeNative(readPath(payload, [{ kind: "field", name: "parameters" }, { kind: "field", name: "token" }], "Write.Token"), write_TokenShape, "Write.Token") as bigint,
  };
}

function encodeLeaseServiceObservation(observation: LeaseServiceObservation): State {
  exactKeys(observation as unknown as Record<string, unknown>, ["accepted", "epoch", "expires", "now", "owners", "writes"], "LeaseServiceObservation");
  const state = Object.create(null) as State;
  state["accepted"] = encodeNative(observation.accepted, leaseServiceAcceptedObservationShape, "LeaseServiceObservation.Accepted");
  state["epoch"] = encodeNative(observation.epoch, leaseServiceEpochObservationShape, "LeaseServiceObservation.Epoch");
  state["expires"] = encodeNative(observation.expires, leaseServiceExpiresObservationShape, "LeaseServiceObservation.Expires");
  state["now"] = encodeNative(observation.now, leaseServiceNowObservationShape, "LeaseServiceObservation.Now");
  state["owners"] = encodeNative(observation.owners, leaseServiceOwnersObservationShape, "LeaseServiceObservation.Owners");
  state["writes"] = encodeNative(observation.writes, leaseServiceWritesObservationShape, "LeaseServiceObservation.Writes");
  return state;
}

export const LeaseServiceSemanticDigest = "a0d5d0fa70f0d62dd55965407a9503b4d220ebcfdc62c0f36d46be0a837b3643" as const;
export const LeaseServiceAsyncTargetProfile = "mirrorecma-async-v1" as const;
export const LeaseServiceAsyncStateComputerContractVersion = "mirrors.async-state-computer/v1" as const;
export const LeaseServiceModelInterface = {
  semanticDigest: LeaseServiceSemanticDigest,
  contract: {"actions":[{"id":"Acquire","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"client"}],"root":"stepParameters"},"id":"Client"}],"wireAction":"acquire","wireAliases":[]},{"id":"Advance","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"amount"}],"root":"stepParameters"},"id":"Amount"}],"wireAction":"advance","wireAliases":[]},{"id":"Release","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"client"}],"root":"stepParameters"},"id":"Client"},{"from":{"path":[{"field":"parameters"},{"field":"token"}],"root":"stepParameters"},"id":"Token"}],"wireAction":"release","wireAliases":[]},{"id":"Renew","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"client"}],"root":"stepParameters"},"id":"Client"},{"from":{"path":[{"field":"parameters"},{"field":"token"}],"root":"stepParameters"},"id":"Token"}],"wireAction":"renew","wireAliases":[]},{"id":"Write","inputs":[{"from":{"path":[{"field":"parameters"},{"field":"client"}],"root":"stepParameters"},"id":"Client"},{"from":{"path":[{"field":"parameters"},{"field":"token"}],"root":"stepParameters"},"id":"Token"}],"wireAction":"write","wireAliases":[]}],"initializers":[{"id":"Initialize","inputs":[],"wireAction":"init","wireAliases":[]}],"interfaceVersion":"1.0.0","model":{"module":"LeaseService","source":"examples/lease-service/specs/LeaseService.tla"},"observations":[{"id":"Accepted","provenance":"implementation","wireName":"accepted"},{"id":"Epoch","provenance":"implementation","wireName":"epoch"},{"id":"Expires","provenance":"implementation","wireName":"expires"},{"id":"Now","provenance":"implementation","wireName":"now"},{"id":"Owners","provenance":"implementation","wireName":"owners"},{"id":"Writes","provenance":"implementation","wireName":"writes"}],"schema":"mirrors.model-interface/v1","wire":{"actionVariable":"action_taken","parameterVariable":"parameters"}},
} as const;
export const LeaseServicePublicManifest = {"actions":[{"id":"Acquire","inputs":[{"id":"Client","type":{"kind":"int"}}]},{"id":"Advance","inputs":[{"id":"Amount","type":{"kind":"int"}}]},{"id":"Release","inputs":[{"id":"Client","type":{"kind":"int"}},{"id":"Token","type":{"kind":"int"}}]},{"id":"Renew","inputs":[{"id":"Client","type":{"kind":"int"}},{"id":"Token","type":{"kind":"int"}}]},{"id":"Write","inputs":[{"id":"Client","type":{"kind":"int"}},{"id":"Token","type":{"kind":"int"}}]}],"initializers":[{"id":"Initialize","inputs":[]}],"interfaceDigest":"a0d5d0fa70f0d62dd55965407a9503b4d220ebcfdc62c0f36d46be0a837b3643","observations":[{"id":"Accepted","type":{"kind":"bool"}},{"id":"Epoch","type":{"kind":"int"}},{"id":"Expires","type":{"kind":"int"}},{"id":"Now","type":{"kind":"int"}},{"id":"Owners","type":{"element":{"kind":"int"},"kind":"set"}},{"id":"Writes","type":{"kind":"int"}}],"schema":"mirrorgate.port/v1"} as const;

export type LeaseServiceBindingErrorCode =
  | "configuration_mismatch"
  | "unknown_action"
  | "transition_before_initialization"
  | "input_shape_mismatch"
  | "adapter_failure"
  | "observation_shape_mismatch"
  | "context_mismatch"
  | "operation_cancelled"
  | "deadline_exceeded"
  | "reentrant_call"
  | "binding_poisoned";

export class LeaseServiceBindingError extends Error {
  constructor(readonly code: LeaseServiceBindingErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "LeaseServiceBindingError";
  }
}

function bindingError(code: LeaseServiceBindingErrorCode, message: string, cause?: unknown): LeaseServiceBindingError {
  return new LeaseServiceBindingError(code, message, cause === undefined ? undefined : { cause });
}

function contextError(context: ReplayContext): LeaseServiceBindingError | undefined {
  if (typeof context.deadline !== "number" || !Number.isFinite(context.deadline)) {
    return bindingError("context_mismatch", "replay deadline must be a finite monotonic instant");
  }
  if (context.signal.aborted) {
    return bindingError("operation_cancelled", "replay operation was cancelled", context.signal.reason);
  }
  if (performance.now() >= context.deadline) {
    return bindingError("deadline_exceeded", "replay deadline expired");
  }
  return undefined;
}

function ensureContextActive(context: ReplayContext): void {
  const error = contextError(context);
  if (error !== undefined) throw error;
}

function awaitPortOperation<T>(operation: PromiseLike<T>, context: ReplayContext): Promise<T> {
  const before = contextError(context);
  if (before !== undefined) {
    void Promise.resolve(operation).catch(() => undefined);
    return Promise.reject(before);
  }
  return new Promise<T>((resolve, reject) => {
    let settled = false;
    let deadlineTimer: ReturnType<typeof setTimeout> | undefined;
    const finish = (callback: () => void): void => {
      if (settled) return;
      settled = true;
      context.signal.removeEventListener("abort", onAbort);
      if (deadlineTimer !== undefined) clearTimeout(deadlineTimer);
      callback();
    };
    const onAbort = (): void => finish(() => reject(
      bindingError("operation_cancelled", "replay operation was cancelled", context.signal.reason),
    ));
    context.signal.addEventListener("abort", onAbort, { once: true });
    const armDeadline = (): void => {
      const remaining = context.deadline - performance.now();
      if (remaining <= 0) {
        finish(() => reject(bindingError("deadline_exceeded", "replay deadline expired")));
      } else {
        deadlineTimer = setTimeout(armDeadline, Math.min(Math.max(1, Math.ceil(remaining)), 2_147_483_647));
      }
    };
    armDeadline();
    void Promise.resolve(operation).then(
      (value) => finish(() => {
        const after = contextError(context);
        if (after === undefined) resolve(value); else reject(after);
      }),
      (error: unknown) => finish(() => reject(error)),
    );
  });
}

type LeaseServiceActionId = "Acquire" | "Advance" | "Initialize" | "Release" | "Renew" | "Write";

export function assertLeaseServiceCompatibleConfig(
  config: Pick<ApalacheConfig, "paramVars">,
): void {
  const expectedParamVar = "parameters";
  const actualParamVar = config.paramVars ?? "";
  if (actualParamVar !== expectedParamVar) {
    throw bindingError(
      "configuration_mismatch",
      "expected paramVars=" + expectedParamVar + ", got " + actualParamVar,
    );
  }
}

export interface LeaseServiceAsyncBinding {
  readonly computer: AsyncStateComputer;
  assertCompatibleConfig(config: Pick<ApalacheConfig, "paramVars">): void;
  coverage(): Readonly<Record<LeaseServiceActionId, number>>;
  assertAllActionsCovered(): void;
}

export function bindLeaseServiceAsync(
  port: LeaseServiceAsyncPort,
  config: Pick<ApalacheConfig, "paramVars">,
): LeaseServiceAsyncBinding {
  assertLeaseServiceCompatibleConfig(config);

  let lifecycle: "fresh" | "initialized" | "poisoned" = "fresh";
  let busy = false;
  const counts: Record<LeaseServiceActionId, number> = {
    "Acquire": 0,
    "Advance": 0,
    "Initialize": 0,
    "Release": 0,
    "Renew": 0,
    "Write": 0,
  };
  const ensureBindingActive = (): void => {
    if (lifecycle === "poisoned") {
      throw bindingError("binding_poisoned", "binding is poisoned");
    }
  };

  const computer: AsyncStateComputer = async ({ action, payload, previous: _previous }, context) => {
    ensureBindingActive();
    if (busy) {
      lifecycle = "poisoned";
      throw bindingError("reentrant_call", "binding permits one callback at a time");
    }
    busy = true;
    let actionId: LeaseServiceActionId;
    let stage: "dispatch" | "input" | "adapter" | "observation" = "dispatch";
    try {
      ensureContextActive(context);
      switch (action) {
      case "acquire":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeAcquireInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.acquire(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Acquire";
        break;
      }
      case "advance":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeAdvanceInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.advance(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Advance";
        break;
      }
      case "init":
      {
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.initialize(context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Initialize";
        break;
      }
      case "release":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeReleaseInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.release(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Release";
        break;
      }
      case "renew":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeRenewInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.renew(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Renew";
        break;
      }
      case "write":
      {
        if (lifecycle === "fresh") throw bindingError("transition_before_initialization", "transition before initialization");
        stage = "input";
        const input = decodeWriteInput(payload);
        stage = "adapter";
        ensureContextActive(context);
        await awaitPortOperation(port.write(input, context), context);
        ensureContextActive(context);
        ensureBindingActive();
        lifecycle = "initialized";
        actionId = "Write";
        break;
      }
        default: throw bindingError("unknown_action", "unknown action " + action);
      }
      stage = "observation";
      ensureContextActive(context);
      const observation = await awaitPortOperation(port.observe(context), context);
      ensureContextActive(context);
      ensureBindingActive();
      const state = encodeLeaseServiceObservation(observation);
      ensureContextActive(context);
      ensureBindingActive();
      counts[actionId] += 1;
      return state;
    } catch (error) {
      lifecycle = "poisoned";
      if (error instanceof LeaseServiceBindingError) throw error;
      const code = stage === "input"
        ? "input_shape_mismatch"
        : stage === "observation"
          ? "observation_shape_mismatch"
          : "adapter_failure";
      throw bindingError(code, "binding failed for action " + action, error);
    } finally {
      busy = false;
    }
  };

  return {
    computer,
    assertCompatibleConfig: assertLeaseServiceCompatibleConfig,
    coverage: () => Object.freeze({ ...counts }),
    assertAllActionsCovered: () => {
      const unseen = (Object.keys(counts) as Array<keyof typeof counts>)
        .filter((id) => counts[id] === 0);
      if (unseen.length > 0) throw new Error("uncovered actions: " + unseen.join(", "));
    },
  };
}

export interface AsyncPublicPort {
  invoke(operationId: string, inputs: Readonly<Record<string, unknown>>, context: ReplayContext): Promise<void>;
  observe(context: ReplayContext): Promise<Readonly<Record<string, unknown>>>;
}

export function bindLeaseServiceAsyncPublicPort(
  publicPort: AsyncPublicPort,
  config: Pick<ApalacheConfig, "paramVars">,
): LeaseServiceAsyncBinding {
  const port: LeaseServiceAsyncPort = {
    initialize: (context) => {
      return publicPort.invoke("Initialize", Object.freeze(Object.create(null) as Record<string, unknown>), context);
    },
    acquire: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Client"] = input.client;
      return publicPort.invoke("Acquire", Object.freeze(values), context);
    },
    advance: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Amount"] = input.amount;
      return publicPort.invoke("Advance", Object.freeze(values), context);
    },
    release: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Client"] = input.client;
      values["Token"] = input.token;
      return publicPort.invoke("Release", Object.freeze(values), context);
    },
    renew: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Client"] = input.client;
      values["Token"] = input.token;
      return publicPort.invoke("Renew", Object.freeze(values), context);
    },
    write: (input, context) => {
      const values = Object.create(null) as Record<string, unknown>;
      values["Client"] = input.client;
      values["Token"] = input.token;
      return publicPort.invoke("Write", Object.freeze(values), context);
    },
    observe: async (context) => {
      const values = ownRecord(await publicPort.observe(context));
      if (values === null) throw new Error("public observation must be a record");
      exactKeys(values, ["Accepted", "Epoch", "Expires", "Now", "Owners", "Writes"], "LeaseServicePublicObservation");
      return {
        accepted: values["Accepted"] as boolean,
        epoch: values["Epoch"] as bigint,
        expires: values["Expires"] as bigint,
        now: values["Now"] as bigint,
        owners: values["Owners"] as MirrorSet<bigint>,
        writes: values["Writes"] as bigint,
      };
    },
  };
  return bindLeaseServiceAsync(port, config);
}
