export {
  runClient,
  runClientWithReport,
  runClientWithTraces,
  runClientWithTracesWithReport,
  runClientGenTraces,
  runClientExplore,
  startExploreSession,
  ExploreSession,
  specFromFile,
  presetClient,
  type RunOptions,
  type GenTracesResult,
  type State,
  type StateComputer,
  type ApalacheConfig,
  type TraceGenerationConfig,
} from "./client.js";

export { specFromFiles } from "./spec.js";

export {
  ReplayControlError,
  type ReplayContext as ReplayCallbackContext,
  type ReplayOptions,
  type ReplayComputer,
  type AsyncStateComputer as AsyncReplayComputer,
} from "./replay-control.js";

export {
  ReplayMismatchError,
  replayReportFromError,
  type ReplayFailure,
  type ReplayReport,
} from "./replay-report.js";

export {
  OpaqueItfValue,
  opaqueItfValue,
  OPAQUE_ITF_MAX_DEPTH,
  OPAQUE_ITF_MAX_NODES,
  type ReadonlyItfValue,
} from "./opaque-itf.js";

export {
  MODEL_INTERFACE_CONTRACT_SCHEMA,
  MODEL_INTERFACE_NEGOTIATION_SCHEMA,
  MODEL_INTERFACE_DESCRIPTOR_SCHEMA,
  MAX_MODEL_INTERFACE_MESSAGE_BYTES,
  MAX_MODEL_INTERFACE_JSON_DEPTH,
  MAX_MODEL_INTERFACE_DESCRIPTOR_BYTES,
  MODEL_INTERFACE_DESCRIPTOR_DIGEST_DOMAIN,
  MODEL_INTERFACE_RESOLVER_SEMANTICS_VERSION,
  MODEL_INTERFACE_COMPARISON_POLICY_VERSION,
  ModelInterfaceProtocolError,
  semanticDigestFromHex,
  parseWireSemanticDigest,
  renderWireSemanticDigest,
  decodeContractV1,
  createVerifyRequest,
  createDescriptorRequest,
  decodeModelInterfaceRequest,
  parseModelInterfaceRequest,
  encodeModelInterfaceRegistration,
  decodeSemanticDescriptor,
  parseSemanticDescriptor,
  canonicalSemanticDescriptorString,
  canonicalSemanticDescriptorBytes,
  semanticDescriptorDigest,
  decodeModelInterfaceReply,
  parseModelInterfaceReply,
  decodeModelInterfaceFailure,
  parseModelInterfaceFailure,
  decodeModelInterfaceMirrorMessage,
  type SemanticDigest,
  type NegotiationPolicy,
  type ModelType,
  type CanonicalItfLiteral,
  type ContractPathSegment,
  type ContractInput,
  type ContractAction,
  type ContractObservation,
  type ContractV1,
  type GeneratedModelInterface,
  type ModelInterfaceVerifyRequest,
  type ModelInterfaceDescriptorRequest,
  type ModelInterfaceRequest,
  type DescriptorRequestOptions,
  type ResolvedInput,
  type ResolvedAction,
  type ResolvedObservation,
  type ResolvedRunProfile,
  type SemanticDescriptor,
  type ModelInterfaceReply,
  type ModelInterfaceFailure,
  type DecodedModelInterfaceMirrorMessage,
} from "./model-interface.js";

export {
  DEFAULT_DESCRIPTOR_CACHE_ENTRIES,
  DEFAULT_DESCRIPTOR_CACHE_BYTES,
  DescriptorCache,
  DescriptorCacheError,
  type DescriptorCacheErrorCode,
  type DescriptorCacheOptions,
  type CachedSemanticDescriptor,
} from "./descriptor-cache.js";

export {
  DynamicBindingError,
  bindDynamicDescriptor,
  bindAsyncDynamicDescriptor,
  type NativeModelValue,
  type NativeModelArray,
  type NativeModelRecord,
  type NativeModelMap,
  type NativeModelVariant,
  type DynamicActionHandler,
  type DynamicObservationHandler,
  type DynamicHandlerRegistry,
  type DynamicBindingErrorCode,
  type DynamicBinding,
  type AsyncDynamicBinding,
  type AsyncDynamicActionHandler,
  type AsyncDynamicObservationHandler,
  type AsyncDynamicHandlerRegistry,
} from "./dynamic-binding.js";

export {
  MIRRORECMA_TARGET_PROFILE,
  MIRRORECMA_ASYNC_TARGET_PROFILE,
  STATE_COMPUTER_CONTRACT_VERSION,
  ASYNC_STATE_COMPUTER_CONTRACT_VERSION,
  NegotiatedRunnerError,
  ModelInterfaceRegistrationError,
  CompiledAdapterRegistry,
  AsyncCompiledAdapterRegistry,
  runClientNegotiated,
  runClientNegotiatedWithReport,
  runClientWithTracesNegotiated,
  runClientWithTracesNegotiatedWithReport,
  type NegotiatedRunnerErrorCode,
  type CompiledAdapterKey,
  type LocalBinding,
  type CallbackLocalBinding,
  type AdapterFactory,
  type CompiledAdapterRegistration,
  type AsyncAdapterFactory,
  type AsyncLocalBinding,
  type AsyncCompiledExecutionSelection,
  type CompiledExecutionSelection,
  type NegotiatedReportRunOptions,
  type CompiledAdapterSelection,
  type DynamicHandlerSelection,
  type DynamicHandlerFactorySelection,
  type DynamicRegistryScope,
  type NegotiatedAdapterSelection,
  type NegotiatedRunOptions,
} from "./negotiated.js";

export {
  DEFAULT_REPLAY_DEADLINES,
  ReplayCancelledError,
  ReplayDeadlineError,
  normalizeReplayDeadlines,
  type ReplayInput,
  type ReplayContext,
  type ReplayDeadlines,
  type ReplayDeadlineStage,
  type AsyncStateComputer,
} from "./async-replay.js";

export {
  replayCleanupFailure,
  type CompiledReplayReport,
  type ReplayDiagnosticReference,
} from "./replay-report.js";

export {
  SANDBOX_PUBLIC_MANIFEST_SCHEMA,
  SANDBOX_ASYNC_TARGET_PROFILE,
  SANDBOX_ASYNC_COMPUTER_CONTRACT,
  SandboxModelError,
  createSandboxPublicManifest,
  createSandboxCompiledModel,
  type SandboxPortableType,
  type SandboxPublicManifest,
  type SandboxPortOperation,
  type SandboxPortObservation,
  type SandboxReplayContext,
  type SandboxNativePort,
  type SandboxAsyncBinding,
  type SandboxAuthoringBundle,
  type SandboxCompiledModel,
  type PreparedSandboxModel,
  type GeneratedSandboxAsyncBinding,
  type GeneratedSandboxModelInput,
} from "./sandbox-model.js";

export {
  evaluateSandboxed,
  sandboxDiagnosticFailures,
  SANDBOX_AUTHORING_OUTPUT_BYTES,
  type SandboxWorkerRuntime,
  type TrustedGateLauncher,
  type SandboxGateEndpoint,
  type SandboxInputRef,
  type SandboxSubmission,
  type SandboxReplayRequest,
  type SandboxTightenedLimits,
  type SandboxAuthoringExecResult,
  type SandboxAuthoringSession,
  type SandboxDisclosurePolicy,
  type SandboxCleanupStatus,
  type SandboxFailureFamily,
  type PublicEvaluationResult,
  type TrustedSandboxDiagnostic,
  type SandboxEvaluationPlan,
  type SandboxEvaluationOptions,
} from "./sandbox.js";

export {
  type ClientMessage,
  type MirrorMessage,
  type Value,
  type ApalacheSpec,
  type TransitionStatus,
  type InvariantStatus,
  type ValidateResult,
  type JobPhase,
  type JobKind,
  type JobOutcome,
  type Register,
  type RegisterTraces,
  type RegisterTraceGen,
  type RegisterValidate,
  type RegisterValidateAsync,
  type RegisterTraceGenAsync,
  type QueryJob,
  type AwaitJob,
  type CancelJob,
  type JobAccepted,
  type JobStatus,
  type JobResult,
  type RegisterExplore,
  type RegisterExploreSession,
  type ExploreAssumeTransition,
  type ExploreNextStep,
  type ExploreQueryState,
  type ExploreCheckInvariant,
  type ExploreAssumeState,
  type ExploreRollback,
  type ExploreDone,
  type ReportState,
  type SpecValidated,
  type InitialState,
  type NextStep,
  type StepOk,
  type StepMismatch,
  type DiffHint,
  type PathSeg,
  renderPath,
  renderDiffHint,
  renderDiffHints,
  type AllStepsDone,
  type GenTracesDone,
  type ProtocolError,
  type RegisterError,
  type ExplorerReady,
  type ExploreTransitionStatus,
  type ExploreStepDone,
  type ExploreState,
  type ExploreInvariantStatus,
  type ExploreAssumeStatus,
  type ExploreRollbackDone,
  type ExploreSessionDone,
  encodeClientMessage,
  encodeState,
  decodeMirrorMessage,
  asInt,
  asStr,
  asRecord,
  getParam,
  getParamInt,
} from "./protocol.js";

export {
  Connection,
  JobHandle,
  runClientValidate,
  RegisterFailedError,
  JobQueueFullError,
  JobEvictedError,
  AsyncOnStdioError,
  ProtocolFailureError,
  ConnectionClosedError,
  type AwaitResult,
  type ConnectionOptions,
  type ValidateOptions,
  type SubmitTraceGenOptions,
} from "./connection.js";

export {
  spawnMirror,
  connectMirror,
  connectTlsMirror,
  MAX_PROTOCOL_LINE_BYTES,
  validateProtocolLine,
  type Transport,
  type ConnectTransport,
  type TlsOptions,
  type TlsConnectTransport,
} from "./transport.js";

export {
  discoverMirrors,
  connectMirrorFromRegistry,
  type MirrorServiceInfo,
  type RegistryOptions,
  type RegistryConnectOptions,
} from "./registry.js";
