export {
  runClient,
  runClientWithTraces,
  runClientGenTraces,
  presetClient,
  connectMirror,
  type State,
  type StateComputer,
  type ApalacheConfig,
  type TraceGenerationConfig,
  type ClientTarget,
  type MirrorEndpoint,
  type StdioEndpoint,
  type TcpEndpoint,
  type TlsEndpoint,
  type RegistryEndpoint,
  type TcpConnectOptions,
  type TlsConnectOptions,
  type ServiceInfo,
} from "./client.js";

export {
  type MirrorMessage,
  type Value,
  type Register,
  type RegisterTraces,
  type RegisterTraceGen,
  type ReportState,
  type SpecValidated,
  type InitialState,
  type NextStep,
  type StepOk,
  type StepMismatch,
  type AllStepsDone,
  type GenTracesDone,
  type ProtocolError,
  type RegisterError,
  encodeClientMessage,
  encodeState,
  decodeMirrorMessage,
  asInt,
  asStr,
  asRecord,
  getParam,
  getParamInt,
} from "./protocol.js";

export {
  spawnMirror,
  connectMirrorTcp,
  connectMirrorTls,
  FingerprintMismatchError,
  type Transport,
} from "./transport.js";

export { discoverServices, type DiscoverOptions } from "./discovery.js";
